#ifndef INCLUDE_CONFIG_HPP
#define INCLUDE_CONFIG_HPP 1

#define TMP_UPDATE_RATE 100
#define ACT_UPDATE_RATE 500

#define ACT_STEP 5
#define ACT_SERVO_PIN 10
#define ACT_SERVO_WAIT_MS 100

#define CTRL_LIDOPEN_WAIT_SEC 20
#define CTRL_LIDOPEN_HISTORY_LEN 30
#define CTRL_LIDOPEN_TEMP_THRESHOLD 25

#define CTRL_TEMP_HISTORY_LEN 30

#define CTRL_GASLOW_HISTORY_LEN 30
#define CTRL_GASLOW_TEMP_THRESHOLD 25


#define CTRL_TEMP_HISTORY_TIMER 1

#define TEMP_SIMULATION 1
#define TEMP_SIMULATION_PIN A1
#define TEMP_SENSOR_PIN A5

#define CONF_WHEEL_PIN A0
#define CONF_BUTTON 6


#define DISP_UPDATE_RATE 100
#define DISP_LCD_ROWS 2
#define DISP_LCD_COLS 20

#define DISP_LCD_PIN_RS 12
#define DISP_LCD_PIN_EN 11
#define DISP_LCD_PIN_D4 5
#define DISP_LCD_PIN_D5 4
#define DISP_LCD_PIN_D6 3
#define DISP_LCD_PIN_D7 2
#endif