#ifndef INCLUDE_CONFIG_HPP
#define INCLUDE_CONFIG_HPP 1

/*Actuator Config*/

#define ACT_STEP 1
#define ACT_SERVO_PIN 10
#define ACT_SERVO_WAIT_MS 100
#define ACT_INVERT_SERVO 0

/*Control Config*/

#define CTRL_LIDOPEN_WAIT_SEC 60
#define CTRL_LIDOPEN_HISTORY_LEN 15
#define CTRL_LIDOPEN_TEMP_THRESHOLD 20
#define CTRL_TEMP_HISTORY_LEN 250
#define CTRL_GASLOW_HISTORY_LEN 250
#define CTRL_GASLOW_TEMP_THRESHOLD 30
#define CTRL_TEMP_HISTORY_TIMER 2

#define TMP_UPDATE_RATE 200
#define ACT_UPDATE_RATE 1000

/*Tempsensor Config*/
//#define TEMP_SIMULATION 1
#define TEMP_SENSOR_PIN A5

/*HMI Config*/
#define CONF_WHEEL_PIN A0
#define CONF_BUTTON 8
#define TEMP_SIMULATION_PIN A1

/*Display Config*/

#define DISP_UPDATE_RATE 200
#define DISP_LCD_ROWS 2
#define DISP_LCD_COLS 20

#define DISP_LCD_PIN_RS 7
#define DISP_LCD_PIN_EN 6
#define DISP_LCD_PIN_D4 5
#define DISP_LCD_PIN_D5 4
#define DISP_LCD_PIN_D6 3
#define DISP_LCD_PIN_D7 2
#endif